
add:
	curl --location --request POST 'http://localhost:8080/tyk/apis/' \
		--header 'x-tyk-authorization: foo' \
		--header 'Content-Type: application/json' \
		-d @goapi.json
	curl --location --request POST 'http://localhost:8080/tyk/apis/' \
		--header 'x-tyk-authorization: foo' \
		--header 'Content-Type: application/json' \
		-d @goapi.json
	curl --location --request POST 'http://localhost:8080/tyk/apis/' \
		--header 'x-tyk-authorization: foo' \
		--header 'Content-Type: application/json' \
		-d @goapi.json
	curl --location --request POST 'http://localhost:8080/tyk/apis/' \
		--header 'x-tyk-authorization: foo' \
		--header 'Content-Type: application/json' \
		-d @goapi.json